
const SLUGS = {
  react:"React", vuejs:"Vue", angular:"Angular", javascript:"JavaScript", typescript:"TypeScript",
  html5:"HTML5", css3:"CSS3", sass:"Sass", less:"Less", tailwindcss:"Tailwind", bootstrap:"Bootstrap",
  jquery:"jQuery", nextdotjs:"Next.js", nuxtdotjs:"Nuxt", svelte:"Svelte", solid:"Solid", vite:"Vite",
  webpack:"Webpack", redux:"Redux", materialui:"MUI", preact:"Preact",
  nodejs:"Node.js", deno:"Deno", bun:"Bun", express:"Express", nestjs:"NestJS", fastify:"Fastify",
  django:"Django", flask:"Flask", fastapi:"FastAPI", spring:"Spring", rails:"Rails", laravel:"Laravel",
  gin:"Gin", quarkus:"Quarkus", dotnet:".NET",
  go:"Go", rust:"Rust", java:"Java", python:"Python", c:"C", cplusplus:"C++", csharp:"C#",
  php:"PHP", ruby:"Ruby", kotlin:"Kotlin", swift:"Swift", dart:"Dart", scala:"Scala",
  elixir:"Elixir", lua:"Lua", r:"R", perl:"Perl", julia:"Julia",
  mysql:"MySQL", postgresql:"PostgreSQL", mongodb:"MongoDB", redis:"Redis", sqlite:"SQLite",
  elasticsearch:"Elasticsearch", supabase:"Supabase", mariadb:"MariaDB", cassandra:"Cassandra",
  neo4j:"Neo4j", amazondynamodb:"DynamoDB",
  prisma:"Prisma", sequelize:"Sequelize", mongoose:"Mongoose",
  docker:"Docker", kubernetes:"Kubernetes", helm:"Helm", terraform:"Terraform", ansible:"Ansible",
  jenkins:"Jenkins", githubactions:"GitHub Actions", argo:"Argo CD", nginx:"Nginx",
  prometheus:"Prometheus", grafana:"Grafana", portainer:"Portainer",
  amazonwebservices:"AWS", googlecloud:"GCP", microsoftazure:"Azure", cloudflare:"Cloudflare",
  vercel:"Vercel", netlify:"Netlify", firebase:"Firebase", digitalocean:"DigitalOcean",
  android:"Android", ios:"iOS", flutter:"Flutter",
  git:"Git", github:"GitHub", gitlab:"GitLab", bitbucket:"Bitbucket", visualstudiocode:"VS Code",
  visualstudio:"Visual Studio", intellijidea:"IntelliJ", pycharm:"PyCharm", webstorm:"WebStorm",
  postman:"Postman", figma:"Figma", canva:"Canva", jira:"Jira", confluence:"Confluence",
  trello:"Trello", slack:"Slack", notion:"Notion", leetcode:"LeetCode", stackoverflow:"Stack Overflow",
  tensorflow:"TensorFlow", pytorch:"PyTorch", keras:"Keras", pandas:"Pandas", numpy:"NumPy", opencv:"OpenCV",
  bytedance:"字节跳动", alibabacloud:"阿里云", baidu:"百度", bilibili:"哔哩哔哩", wechat:"微信",
  zhihu:"知乎", xiaohongshu:"小红书", meituan:"美团", huawei:"华为", xiaomi:"小米", taobao:"淘宝",
  alipay:"支付宝", tencentqq:"QQ", kuaishou:"快手", lenovo:"联想", oppo:"OPPO", vivo:"vivo", dji:"大疆",
  juejin:"掘金", neteasecloudmusic:"网易云音乐", sogou:"搜狗", tiktok:"TikTok",
};
const fs=await import("node:fs/promises");
// 1. 全量 JSON → title→hex 映射
const titleToHex={};
try{
  const jr=await fetch("https://cdn.jsdelivr.net/npm/simple-icons/_data/simple-icons.json");
  const arr=await jr.json();
  for(const i of arr){ if(i.title&&i.hex) titleToHex[i.title]=i.hex; }
}catch(e){console.log("hex JSON 失败: "+e.message);}
const rePD=/<path[^>]*\sd="([^"]+)"/, reT=/<title>([^<]+)<\/title>/;
const entries=Object.entries(SLUGS);
const out={}; const miss=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
for(const [slug,label] of entries){
  for(let a=0;a<3;a++){
    try{
      const r=await fetch(`https://cdn.jsdelivr.net/npm/simple-icons/icons/${slug}.svg`);
      if(r.status===429){await sleep(600*a);continue;}
      if(!r.ok){miss.push(slug+"(404)");break;}
      const t=await r.text();
      const pm=rePD.exec(t), tm=reT.exec(t);
      if(!pm){miss.push(slug+"(no-path)");break;}
      const svgTitle=tm?tm[1].trim():null;
      const hex=svgTitle&&titleToHex[svgTitle]?"#"+titleToHex[svgTitle]:null;
      out[slug]={label, d:pm[1], viewBox:"0 0 24 24", hex, title:svgTitle};
      break;
    }catch(e){await sleep(300*a);}
  }
}
try{
  const z=await fs.readFile(String.raw`C:\Users\mi\Downloads\智联招聘.svg`,"utf8");
  const pd=rePD.exec(z);
  if(pd) out.zhaopin={label:"智联招聘",d:pd[1],viewBox:"0 0 1024 1024",hex:"#002AFF",source:"iconfont"};
}catch(e){miss.push("zhaopin(err)");}
const withHex=Object.values(out).filter(i=>i.hex).length;
const code=`// AUTO-GENERATED by build-catalog.mjs. Sources: Simple Icons (CC0) + iconfont 转载(合理使用).
// 不要手改。重新生成: node lib/icons/build-catalog.mjs
export const ICON_CATALOG = ${JSON.stringify(out,null,2)};
export const ICON_SOURCES = { simpleicons: "CC0 1.0", iconfont: "转载-合理使用" };
`;
await fs.writeFile(String.raw`E:\vsws\deepseek-harness-plugins\1-插件源码\dsh-campus-job\lib\icons\catalog.js`,code);
console.log(`catalog.js: ${Object.keys(out).length} 图标 (${withHex} 带品牌色), miss: ${miss.length?miss.join(", "):"无"}`);

